[options]
admin_password = odoo
addons_path = /home/wai-phyo-htet/Documents/odoo_source_code/odoo19e_dec18/odoo/addons,/home/wai-phyo-htet/Documents/integration_with_social_platform
db_host = localhost
db_user = odoo
db_password = odoo
db_name = integration_social_db